### ISSUE TITLE
The Readme needs a disclaimer of some kind that not all decorators may be safe to trim off

### ISSUE THREAD

**Issue by DandelionSprout** [purl-sanitizer/purl#1]
Hello, Dandelion Sprout here, one of the question askers at your Summit speech. I found the repo through checking a source note in the Summit VoD.

So, I figured I could try to convert https://raw.githubusercontent.com/purl-sanitizer/purl/main/data/tracking_link_decorations.txt into [adblock format](https://github.com/DandelionSprout/adfilt/blob/f2aaa8bede93ad31ae6535bb32bfe5c788e01444/LegitimateURLShortener.txt#L1487-L1698), by taking most of those that occured more than 10 times in your list and then have them apply to all sites.

Didn't take me all that long before problems arose. Removing `msToken` apparently [broke TikTok](https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-7221071), which although your repo only listed msToken as removable on 3rd-party sites, still makes wonder whether that parameter should've been removed from any sites.

The day after, `traceId` turned out to [break Microsoft Dynamics Business Central](https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-7228224). I lacked info from the reporter about whether `hubspot.com` was involved on MDBC or not, however. There's also some parameters that don't look safe to me to block on *any* site no matter what, stuff like `client_id`, `session_id`, `repeat_visitor`, `desturl`, etc.

Overall, the Readme seems a bit small at the moment, and I take a guess that it could need some "Best use" guidelines or such. Stuff like "How are the parameters intended to be used?", "Are the rows in tracking_link_decorations.txt specifically intended to be site-specific?", "How are new rows added to the file?", etc.

**Comment by purl-sanitizer** [comment]
Hi, thank you for bringing this to our attention, and I apologize for not responding earlier, the repository was on hold due to an issue with an API token. As PURL relies on certain behaviors there's a possibility that some false positives will occur where the link decoration behaves in a similar fashion to other tracking link decorations in our dataset. I have taken a look at ```msToken``` in our dataset and it does appear to behave in a suspicious manner, where it is set directly by a response from ByteDance and is being heavily connected with other scripts and nodes in the webpage, a few of which are also loading advertisements in particular, and is a very high entropy string. This is the same case as ```traceId``` as well.

**Comment by purl-sanitizer** [comment]
Hi, thank you for bringing this to my attention, and I apologize for not responding earlier, the repository was on hold due to an issue with an API token.

As PURL relies on certain behaviors there's a possibility that some false positives will occur where the link decoration behaves in a similar fashion to other tracking link decorations in our dataset. I have taken a look at ```msToken``` in our dataset and it does appear to behave in a suspicious manner on some sites, where it is set directly by a response from ByteDance and is heavily connected with other scripts and nodes in the webpage, a few of which are also loading advertisements in particular, and is, in general, a very high entropy string. This is the same case for ```traceId``` as well. I am looking more into these cases and the others you have mentioned to see if they are indeed functional and if PURL's pipeline needs to be updated to accommodate such cases.  

In our dataset, we found 635 instances where ```traceId``` should not be removed and 383 instances where it should be removed. Similarly, 51 instances of ```msToken``` should not be blocked and 44 instances should be removed. The difference in where the link decoration is supposed to be removed or allowed comes from the combination of the main website itself and the request domain as well. So they are indeed site- and domain-specific cases, as the same link decoration might be used by other request domains for functional purposes. I will update the README to provide this distinction.

Thank you again for bringing this to my attention.
